### ISSUE TITLE
看起来似乎很美...但是...

### ISSUE THREAD

**Issue by Tarhyru** [facert/awesome-spider#34]
随便点了几个爬虫发现已经很久没维护了......估计大都不能用了吧...

**Comment by manuzhang** [comment]
https://github.com/dontcontactme/doubanspiders, 404

**Comment by irsunshine** [comment]
这里标注的大部分爬虫，逻辑都不复杂，至于你说的不能用，自己改改就行了

**Comment by WuMing757** [comment]
可以加上推荐每个项目时的时间吗？这样方便选择。谢谢

**Comment by OneCodeMonkey** [comment]
微博爬虫是一直在维护的。
